SELECT F.ID,
       N.FISH_NAME,
       F.LENGTH
FROM FISH_INFO AS F
JOIN FISH_NAME_INFO AS N
  ON F.FISH_TYPE = N.FISH_TYPE
JOIN (
    SELECT FISH_TYPE,
           MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS M
  ON F.FISH_TYPE = M.FISH_TYPE
 AND F.LENGTH = M.MAX_LENGTH
ORDER BY F.ID;