SELECT 
    SUM(c.SCORE) AS SCORE,
    a.EMP_NO,
    a.EMP_NAME,
    a.POSITION,
    a.EMAIL
FROM HR_EMPLOYEES a
JOIN HR_GRADE c ON a.EMP_NO = c.EMP_NO
WHERE c.YEAR = 2022
GROUP BY a.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;